### ISSUE TITLE
[Question] Can the lib work standalone or needs `cacheman` package dependency?

### ISSUE THREAD

**Issue by aga5tya** [cayasso/cacheman-redis#16]
I'm looking at implementing cacheman-redis package, but right now readme specifies that it could be used just by importing the lib. But cacheman repo specifies engine can me used and imported along. Are there some benefits/drawbacks using them standalone and combined ? cc/ @cayasso

**Comment by khmm12** [comment]
In most cases `cacheman` plays a role of proxy, which calls engine functions as is with slight differences.

But there is 3 primary differences:
1. `cacheman` provides 2 APIs: callbacks and promises from out of box.
2. `cacheman` provides `wrap` method, which is some kind of sugar, but useful

example:
```js
const key = JSON.stringify(params)
const report = await cache.wrap(key, TTL, () => prepareMassiveReport(params))
res.json({ report })
``` 
3. `cacheman`, because is a high level wrapper, allows you to use and change different engines depending on requirements without difficulty.

_a bit of my controversial opinion_
If you're ardent supporter of own high level abstractions, you don't find any advantage of `cacheman` and probably `cacheman-redis` over any favourite `redis` client. In other cases `cacheman` + `cacheman-redis` together is good choice.

**Comment by cayasso** [comment]
Cloaing because question has been answered ;)
